### ISSUE TITLE
How does town do "partial cluster update"?

### ISSUE THREAD

**Issue by kevinsimper** [lookify/town#1]
The documentation says it can do "partial cluster update". How does it exactly happen?

**Comment by kiril-me** [comment]
When you first time execute command

```
town run
```

This will up whole cluster. During development you can update one of the docker images and restart your cluster with the same command. Town will check all running containers. If it finds that the image has been changed, it will stop and remove all dependent containers. Next step the Town rebuilt up part of the dependency tree.

For example redis container rarely changes and you wouldn't want to restart it.

**Comment by kevinsimper** [comment]
Okay so it does a `docker pull` to check if there is a new version, where you would have to do it yourself if you were using `docker-compose`?

**Comment by kiril-me** [comment]
Unfortunately no. Town check only local repository. But this is good question, perhaps we should add this.

**Comment by kevinsimper** [comment]
How is this a benefit from docker-compose, a container only takes seconds to restart?

**Comment by kiril-me** [comment]
Docker-compose restart whole set of containers. Town try to optimize it and restart only necessary.

**Comment by kevinsimper** [comment]
It does not seem like a great benefit

**Comment by kiril-me** [comment]
Depends on how big is your cluster and how often you make new builds. We decrease 50% of our deployment time.
Plus we use dynamic variables to configure Zookeeper and Cassandra.
